export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
  { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
  { code: 'da', name: 'Danish', flag: '🇩🇰' },
  { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
  { code: 'no', name: 'Norwegian', flag: '🇳🇴' },
  { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
];

export const CEFR_LEVELS = [
  { code: 'A1', label: 'A1 — First Basics', description: 'Simple words and phrases' },
  { code: 'A2', label: 'A2 — Elementary', description: 'In-depth basics' },
  { code: 'B1', label: 'B1 — Intermediate', description: 'Good conversational ability' },
  { code: 'B2', label: 'B2 — Upper Intermediate', description: 'Fluent on most topics' },
  { code: 'C1', label: 'C1 — Advanced', description: 'Fluent / Business fluent' },
  { code: 'C2', label: 'C2 — Proficient', description: 'Native-like mastery' },
];
