export const LANGUAGE_NAMES: Record<string, string> = {
  en: 'English',
  de: 'German',
  fr: 'French',
  es: 'Spanish',
  it: 'Italian',
  pt: 'Portuguese',
  nl: 'Dutch',
  ru: 'Russian',
  zh: 'Chinese (Mandarin)',
  ja: 'Japanese',
  ko: 'Korean',
  ar: 'Arabic',
  hi: 'Hindi',
  tr: 'Turkish',
  pl: 'Polish',
  sv: 'Swedish',
  da: 'Danish',
  fi: 'Finnish',
  no: 'Norwegian',
  uk: 'Ukrainian',
};

export const CEFR_DESCRIPTIONS: Record<string, string> = {
  A1: 'A1 level: absolute beginner (first basics, simple words and phrases)',
  A2: 'A2 level: elementary (in-depth basics, simple sentences)',
  B1: 'B1 level: intermediate (good conversational ability)',
  B2: 'B2 level: upper-intermediate (fluent, can discuss most topics)',
  C1: 'C1 level: advanced (fluent/business fluent, nuanced expression)',
  C2: 'C2 level: proficient (native-like mastery)',
};
